"""mensaje de la migración

Revision ID: ae65b1e00722
Revises: 
Create Date: 2023-05-28 15:14:41.034249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae65b1e00722'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('idProducto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombreProducto', sa.String(length=250), nullable=True),
    sa.Column('desProducto', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('idProducto')
    )
    op.create_table('proveedor',
    sa.Column('idProveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombreProveedor', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('idProveedor')
    )
    op.create_table('usuarios',
    sa.Column('idUsuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombreUsuario', sa.String(length=250), nullable=True),
    sa.Column('correo', sa.String(length=250), nullable=False),
    sa.Column('contraseña', sa.String(length=250), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idUsuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('ventas',
    sa.Column('idVenta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('idVenta')
    )
    op.create_table('imagen_producto',
    sa.Column('id_imagen', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('renderate_date', sa.Text(), nullable=False),
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idProducto'], ['producto.idProducto'], ),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagen_producto')
    op.drop_table('ventas')
    op.drop_table('usuarios')
    op.drop_table('proveedor')
    op.drop_table('producto')
    # ### end Alembic commands ###
